version: 2
registries:
  npm-registry-npm-pkg-github-com:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: "${{secrets.NPM_REGISTRY_NPM_PKG_GITHUB_COM_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: vue
    versions:
    - 3.0.5
    - 3.0.6
    - 3.0.7
    - 3.0.9
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.10
    - 7.13.12
    - 7.13.8
    - 7.13.9
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: "@vue/test-utils"
    versions:
    - 2.0.0-rc.3
    - 2.0.0-rc.4
  - dependency-name: semantic-release
    versions:
    - 17.4.1
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
  registries:
  - npm-registry-npm-pkg-github-com
