sudo: false
dist: trusty

language: node_js
node_js:
  - "6"
  - "7"
  - "8"
  - "9"
  - "node"

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

script:
  - yarn lint
  - yarn test
  - yarn prepublish
