dist: trusty

language: node_js
node_js:
  - "8"
  - "10"
  - "node"

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

cache:
  yarn: true
  directories:
    - node_modules
    - ~/.npm
    - ~/.cache

script:
  - yarn lint
  - yarn test
  - yarn prepublish

jobs:
  include:
    - stage: Release
      if: branch = master AND type = push
      node_js: node
      script: yarn semantic-release

